### ISSUE TITLE
Localisation problems!

### ISSUE THREAD

**Issue by eo22** [laravel-enso/Enso#120]
This is request.

### Prerequisites
* [y] Are you running the latest version?
* [ y] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ y] Did you check the documentation?
* [ y] Did you perform a cursory search?

### Description
When I make composer update than flags.scss removes some lines, can you help me?!

**Comment by aocneanu** [comment]
Ok buddy, hear me on this...

That's your n'th issue in the last few days, and all of them have a similar approach.

You throw questions of one cryptic line because, probably, you don't have time to waste. Don't worry, my role here is trying to understand what you're saying, and if I don't I'll ask clarifications.

At first you completely ignored the issue template. Thank you so much that in your most recent ones you decided to use it. And you guessed well, the issue template is just a formality, but it's still better if you check all the boxes.

> This is request.

👍 

> [y] Are you running the latest version?

probably not.

> [ y] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)

no, you're not. We have a localisation repository, and the core where this file come from, but I insist, don't waste time trying to understand how this works, in the end you just want a flag icon (today)

> [ y] Did you check the documentation?

of course not, you don't have time for that.

Imagine the amount of time that our team spent for creating the docs, especially @gandesc. But maybe it's too big for you, so don't worry, just ask anything and I will look it up for you.

> [ y] Did you perform a cursory search?

nope, 'cause you're efficient with your time. Nobody could asked this before.

> Description
When I make composer update than flags.scss removes some lines, can you help me?!

Thank you for the detailed description. Anyway I love solving quest questions, and I enjoy the exclamation mark at the end, it makes me motivated.

Now coming back to your question, I'm assuming that you are modifying `flags.scss`, which you shouldn't. (there is a mistake in the localisation docs that I will fix now, but I simply can't think that you stumbled on it.)

A few days ago, when you had another issue on icons, I directed you to a specific part of the documentation, that is covering "Icons":

![image](https://user-images.githubusercontent.com/16073274/43240490-6d28fc76-909f-11e8-995e-15a23572f2f3.png)

You read the first line, because at that point you wanted a menu. Now you want a flag, so please read at least the second line.

Let me know if I was helpful.

P.S. If you have another idea coming, don't waste time opening another issue. Use this one, it's simpler.

**Comment by eo22** [comment]
Thank you for your answer and help!
 
I've imported flag icons as it's specified in documentation and now it's working ok.
Now I have another question, I need to change the width of menu section because I've added some menu item with long text.
I've make changes on resources/assets/js/core/structure/VueAside.vue but I think it's not good idea because after compiling it reverts the code again. So, can you please help me?

Thanks again for your help!

![screen shot 2018-07-26 at 11 19 57](https://user-images.githubusercontent.com/37216194/43253874-42ca7cda-90c6-11e8-9122-1d13f21fc1f7.png)
