### ISSUE TITLE
Fontawesome won't install after latest update

### ISSUE THREAD

**Issue by JoshZA** [laravel-enso/Enso#123]
This is  a **bug**.

Output when running yarn install:

```
yarn install v1.9.2
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/free-brands-svg-icons/-/free-brands-svg-icons-5.2.0.tgz: Request failed \"401 Unauthorized\"".

```

**Comment by aocneanu** [comment]
maybe https://github.com/FortAwesome/Font-Awesome/issues/13682 ?

**Comment by JoshZA** [comment]
I deleted yarn.lock from the repo, and then everything installed correctly

Thank you

**Comment by bleeuwen** [comment]
Deletion of yarn.lock worked for me too (Laravel/Enso version 2.15.1)

**Comment by robbykrlos** [comment]
I just had a problem with font-awesome recently and seems to be something in common with this topic, 

We had the pro version for 1 year, and while subscription was active, we had been using latest versions of font-awesome, including one of the pro packages - `duo-tone`, using the npm authorization with the provided token.

Since the sub was ending, we decided to use the pro package offline - hosted by us - but kept using the "free" packages online:

```
        "@fortawesome/fontawesome-free": "^5.15.3",
        "@fortawesome/fontawesome-svg-core": "^1.2.35",
        "@fortawesome/free-brands-svg-icons": "^5.15.3",
        "@fortawesome/free-regular-svg-icons": "^5.15.3",
        "@fortawesome/free-solid-svg-icons": "^5.15.3",
        "@fortawesome/vue-fontawesome": "^2.0.0",
```

Since we did not use any of the pro packages, we removed the `.npmrc` authentication.

Since 1 week ago (but let's say ~beginning of December) on a clean yarn install we got this error:

```
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/fontawesome-svg-core/-/1.2.36/fontawesome-svg-core-1.2.36.tgz: Request failed \"401 Unauthorized\"".
info If you think this is a bug, please open a bug report with the information provided in "yarn-error.log".
```

Weird, since we had this working without auth token for 3-4 months.

I've contacted FA support, but they were very short in answers and avoided telling me if there is a way to run free icons online without active sub,

I read some of your threads, but also some of the issues opened on font-awesome repo (where I saw also @aocneanu active) and figured out that not all "free" versions are actually free, and maybe recently the 5.3 versions were made private?! Not sure about this.

What I know is that since we are not using a token anymore, we had to roll-back to these versions (which are enso's defaults in package.json):

```
        "@fortawesome/fontawesome-free": "^5.2.0",
        "@fortawesome/fontawesome-svg-core": "^1.2.2",
        "@fortawesome/free-brands-svg-icons": "^5.2.0",
        "@fortawesome/free-regular-svg-icons": "^5.2.0",
        "@fortawesome/free-solid-svg-icons": "^5.2.0",
        "@fortawesome/vue-fontawesome": "^0.1.1",
```

And no auth was required anymore. I did not manage to find this online - which versions are public, and which are private.
The package.json changes on versions were done with full clean.

```
rm -rf node_modules
rm yarn.lock
yarn clean cache
yarn instal
```

Maybe the explanations are not 100% accurate, but maybe it helps someone in the same situation, since the solution seems to be working.
