### ISSUE TITLE
Right side nav bar icons disappear when browser is 1039px-1087px

### ISSUE THREAD

**Issue by TylerGauntlett** [laravel-enso/Enso#125]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
When the viewport is 1039px-1087px, all icons/buttons disappear from the top right. They do not appear to be accessible from anywhere else.

### Steps to Reproduce
1. Open chrome tools on the page so the viewport size is viewable
2. Change the window size between 1039px and 1087

### Expected behavior
This viewport range should show icons similar to those shown when greater than 1087px (with notifications) or less than 1039px (without notifications).

### Actual behavior
The icons/buttons disappear completely and are unaccessible.

**Comment by TylerGauntlett** [comment]
<img width="1025" alt="screen shot 2018-08-08 at 2 58 03 pm" src="https://user-images.githubusercontent.com/13861069/43858818-ffe254a4-9b1c-11e8-9f81-eb0b239cf488.png">

**Comment by aocneanu** [comment]
It seems to be related to this https://github.com/jgthms/bulma/issues/2040

**Comment by jlsjonas** [comment]
Note that this can be _fixed_ by reverting their gap change to `$gap: 32px;` **before** importing the initial-variables lines in (since the theming update) `vendor/laravel-enso/core/src/resources/sass/themes/dark.scss` & `vendor/laravel-enso/core/src/resources/sass/themes/light.scss` for the dark & light theme respectively.

(these files get published to your resources folder; so you can modify it there directly too in case this _fix_ isn't suitable for the framework itself)

**Comment by jlsjonas** [comment]
Fixed this specific issue by removing the v-if's in the navbar and replacing them with `is-hidden-desktop` and `is-hidden-touch`. since this way the whole part is controlled by bulma; and mismatching won't cause dissapearing issues on it. We might just consider DRY instead though... (but `navbar-brand` is causing issues for that so it would need a bigger refactor)
