### ISSUE TITLE
Question:  Why 1-42.js files?

### ISSUE THREAD

**Issue by corepay** [laravel-enso/Enso#135]
This is  a *question**.

### Prerequisites
* [x ] Are you running the latest version?
* [x ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x ] Did you check the documentation?
* [x ] Did you perform a cursory search?

### Description

![image](https://user-images.githubusercontent.com/37046197/44940861-491f7a00-ad62-11e8-9808-5cd3bd135cd1.png)

What are these files for?  Can they be removed?  There is some content in them that baffles me as to why it is needed:

![image](https://user-images.githubusercontent.com/37046197/44940867-62282b00-ad62-11e8-9b54-9cef061bb858.png)

**Comment by aocneanu** [comment]
>What are these files for? Can they be removed? There is some content in them that baffles me as to why it is needed:

Enso uses code splitting and async component loading. The whole front end of Enso is Vue and webpack is translating vue into these javascript files in the compiling process. Btw, the files are pretty big because the demo version is not compiled with production (not minimized).

No, the files cannot be removed without breaking functionality for certain pages / components.

About the content, it looks like a dictionary or something.A lot of fucking, indeed :) It may have something to do with the lib that Enso's using for calculating the password complexity, dropbox's [zxcvbn](https://github.com/dropbox/zxcvbn).
