### ISSUE TITLE
Disable ActionLogger for specific routes

### ISSUE THREAD

**Issue by stotes** [laravel-enso/Enso#204]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
Is it possible to disable the actionlogger for specific actions?

**Comment by aocneanu** [comment]
Right now you can't specifically except routes from the logger,  but there are a few ways to deal with this.

The middleware is registered under the `core` middleware group and applied on all Enso's core packages out of the box. For each local route while using the `core` middleware group `action-logger` will be available too.

You can disable it at the framework level by overwriting the `core` group in your local `AppServiceProvider`

```php
        $this->app['router']->middlewareGroup('core', [
            VerifyActiveState::class,
//          ActionLogger::class,
            Impersonate::class,
            VerifyRouteAccess::class,
            SetLanguage::class,
        ]);
```

You can define a new group that will exclude `action-logger` and use that group only on the routes or route groups where you want it excluded

Could you share the reasons behind the need to avoid it on specific routes? I'm just curious because until now I've never encountered a situation where I needed it removed.

**Comment by stotes** [comment]
Thanks Adrian. 
I'll look into what you have suggested.

I am running "long-running-queue" items and am using the https://github.com/imTigger/laravel-job-status package to pull back their status. My Vue component is calling a progress axios get call every 5 seconds and some of these jobs take hours to run. 

As you can imagine the actionlog table is filled with these requests.

Appreciate your help and as always I love your work!
Cheers

**Comment by aocneanu** [comment]
Thanks,

I think that for your situation you could use websockets. Look at the implementation for laravel-enso/io where we track progress for background jobs.
