### ISSUE TITLE
The question is: How can I use a custom form for people on version 3.5.0?

### ISSUE THREAD

**Issue by elysiopires** [laravel-enso/enso#250]
This is a question...

### Prerequisites
* [X] Are you running the latest version? YES
* [X] Are you reporting to the correct repository? YES
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [X] Did you check the documentation? YES
* [X] Did you perform a cursory search? YES

### Description
I was trying to do the same thing that I did before with a project using enso 3.3.5, replace the people form template and table template too.

On this version, I could only change the config/people.php and change the lines bellow pointing to my custom files:

> return [
>     'formTemplate' => null,
>     'tableTemplate' => null,
> ];

Since version 3.4.0(people package people 2.2.*) this file goes away... and I saw the version 3.5.0 and still missing... so I checked the change backlog and I found:

> people
> 
> improves form for easier customization
> adds AvoidsDeletionConflicts, Relations, Rememberable on Person
> adds laravel-enso/enums
> adds EnumServiceProvider
> adds bank and bank_account to the table's migration
> adds uid to $queryAttributes in Option
> removes people.php config file
> 

So the question is: How can I use my custom form template for people, company or any enso package?

Sincerely,
Elysio

### Expected behavior
Use a custom form template on enso.

### Actual behavior
Cannot use anymore file config/people.php to set my custom form to people.

**Comment by aocneanu** [comment]
Hi @elysiopires,

Create a local versions for `CompanyForm.php` and `CompanyTable.php` that can extend the ones in `laravel-enso/companies` and customize exactly what you need.

For instance since the `TemplatePath` constant is protected, you can only override that if you only need a different template.

Then make sure that in the local `AppServiceProvider` you add to the bindings prop the local classes

```
public $bindings = [
    CoreCompanyForm::class => CompanyForm::class, //(`CompanyForm` is the local class)
    CoreCompanyTable::class => CompanyTable::class, //(`CompanyTable` is the local class)
]
```

Since in the controllers we resolve the builder class from Laravel's service container  this should be everything.

**Comment by elysiopires** [comment]
Hello @aocneanu !

Worked like a charm!

Thx for your support... You could add this to Enso Documentation!

Thx,
Elysio Pires
