### ISSUE TITLE
Document Title Pre/Postfix

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/Enso#39]
At the moment if you activate extendedDocumentTitle in config the application name is added as postfix to document title:
- Document Title: APPLICATION_NAME | Page name

It would be nice if you can configure if the name should be added as post/or prefix
- New config: extendedDocumentTitlePosition: pre|post
- If pre: Document Title = APPLICATION_NAME | Page name
- If post: Document Title = Page name | APPLICATION_NAME

Maybe add another configuration for separator (default |)

If not possible change it to postfix by default, I think its more often useful as postfix than as prefix

**Comment by gandesc** [comment]
Personally, I would vote for leaving out application name completely and using the favicon as a means to visually identify the application. If bookmarked, the favicon will be shown.

Obviously, having the page title/name is useful.

As a sidenote, we will have some mechanism to show notifications (like Slack for instance), maybe also show the number of notifications, so we can definetily use more tab space real-estate.

@aocneanu what do you think?

**Comment by mauthi** [comment]
I think with the already added config it’s fine so the user can decide if he needs title or not - ticket is just for adding the possibility to add it as pre or post

**Comment by aocneanu** [comment]
I kinda' feel that we allowed the document title to be prolonged, and that's not really ergonomic (let me say "I said so" :P ) and now we're adding a new option to the config to fix this.

When I bookmark a site and then need it later, I just use the browser's built in bookmark filtering, i'm not browsing through labels. So as far as I'm concerned, I'll never use this feature.

Regarding the config, in my opinion the best config is no config. But because it's hard to automatise everything, we need to add important options there. I think that the document title formatting is just too trivial to have not one but two options for configuring it.

Give the fact that we already have an implementation, I would suggest deciding if the app's name should be concatenated before or after the title, and leave a single flag for that.

If this feature will be requested / voted by more users, we'll rethink the implementation.

How does that sound?

**Comment by mauthi** [comment]
Ok, then we decide now to concatenate the app name after the page title and leave the one flag for activating/deactivating this?

**Comment by aocneanu** [comment]
Yep.

**Comment by mauthi** [comment]
@gandesc 
> As a sidenote, we will have some mechanism to show notifications (like Slack for instance), maybe also show the number of notifications, so we can definetily use more tab space real-estate.

I think this should go to #40 ?
