### ISSUE TITLE
After update to 4.9.1 /api/broadcasting/auth is called 3 times but every call fails with status 419 and push notifications are not working anymore

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/enso#415]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

After login / reload I see the following in my console:

<img width="490" alt="image" src="https://user-images.githubusercontent.com/7204559/155851118-7585e443-690c-4503-afa5-3b707f9a5b4a.png">

<img width="642" alt="image" src="https://user-images.githubusercontent.com/7204559/155851128-63e8c3be-d09a-4dd7-82f0-eb0f95955145.png">

In addition to that I don't get any toast message or pusher updates anymore - I think this is related to that?

Maybe the error is related to https://github.com/laravel-enso/enso/issues/351?

**Comment by aocneanu** [comment]
Hi Mauthi,

This is fixed in v5.0.

The culprit for v4.x is this commit https://github.com/laravel-enso/core/commit/8ee62af14fac8a5db4d1a0ba1217316738578503

Before upgrading to v5.0, you can either extend the Meta in the local project and bind it to the container, or make sure you require an older version of core, that has the csrf token included.

**Comment by mauthi** [comment]
Updated to 5.0.0 today and it works. Thx!
