### ISSUE TITLE
vuetable error if below 7 column defined in table.json

### ISSUE THREAD

**Issue by shonhor22** [laravel-enso/Enso#70]
If i deleted 1 or 2 column from users.json datatable not render and return below console error. 
maybe it is required minimum 7 column or any other error.

![image](https://user-images.githubusercontent.com/8970793/37255680-a39086ba-258a-11e8-8bdb-6b1e55baf7ba.png)

**Comment by pongraczi** [comment]
You should modify much more after you modified the datatable, because the internal logic expects these deleted columns.  
In your case, **status** column is really necessary.

**Comment by aocneanu** [comment]
@shonhor22, this is happening because the table saves in the browser's localStorage the settings of each table once you change something in it's configuration. I will have to improve the lib to handle this situation.

For now just delete the entry for the settings for the according table. I attached a picture for the users table and google chrome.

![image](https://user-images.githubusercontent.com/16073274/37267544-ab2acea0-25c9-11e8-947b-1fb010c05c54.png)

Let me know if it works after you remove this entry.

**Comment by shonhor22** [comment]
after removed chrome localstorage vuetable worked
