### ISSUE TITLE
Stateless auth - Laravel Passport

### ISSUE THREAD

**Issue by peterbabic** [laravel-enso/Enso#71]
Hello, that is some really nice work you have done here!

I would really like to have deeper understanding of why it become impossible to have stateless auth using JWT and also why didn't you use the Laravel Passport for it.

Would it be reasonable amount of work to add it, if there was need for 3rd party API auth?

Thanks

**Comment by aocneanu** [comment]
Hi @peterbabic,

Thank you for your appreciation.

It's not impossible to have stateless auth.  In fact, the first version of Enso had JWT instead of conventional auth. But we decided to drop JWT because we didn't found any real pros for it, but we did find a few cons.

To migrate the auth over JWT would mean a few hours of work, and I'm willing to do it if somebody can give me the right arguments.

Cheers

**Comment by peterbabic** [comment]
Hi @aocneanu,
thank You for the response. I was specifically interested in [Laravel Passport](https://laravel.com/docs/5.6/passport) which is officially supported package to work with JWT.

I was interested in if it was considered, or why was it refused. Or did the project start before the package became officially supported and now is too late to implment it?

Although you are writing in some detail in the readme and here about the JTW, there was still no mention about Lasravel Passport.

Thank you

**Comment by aocneanu** [comment]
@peterbabic 
I think that maybe you are making a small confusion (the same that I did at the time).

Laravel Passport is not, in fact,  "the official package to work with JWT". It's the official package to work with OAuth2, which is something different, AND it uses a JWT token.

In Enso, unless we want to make 3rd party auth (let's say that we want to allow users to login with their Github credentials), we don't need OAuth2, nor Passport. We can use directly JWT Auth.

If I'm missing something don't hesitate to mention it.
