### ISSUE TITLE
How to override data migrations?

### ISSUE THREAD

**Issue by disciplego** [laravel-enso/Enso#95]
Some migrations from the core and other packages override fine by copying the migration file to database/migrations, but some do not. For instance:

insert_default_owner -- works as expected
insert_default_user -- runs the package migration even if copied to the database/migrations folder

Am I missing something??

**Comment by aocneanu** [comment]
In theory, if you copy a migration from a package to database/migration you should get an error because you have now a duplicate class name.

I think that the clean approach would be creating a new migration "2017_01_01_aTimestampAfterTheOriginalUserInsertMigration_insert_my_users" where you do `User::truncate()` and insert your  own users.

**Comment by Aubrey-Robertson** [comment]
Thank you for the response. You will get a duplicate class name error if the timestamp is different. Just seemed odd that some work and some don't.

I will create new migrations and truncate as suggested. Thanks again.

**Comment by aocneanu** [comment]
Ah, cool, I never knew that. Tomorrow I will set up a new project and test, maybe we will figure it out.

**Comment by aocneanu** [comment]
I just tested and it seems that the migrations from packages have a higher priority. This is expected due to the order of loading the service providers.

But I think that it would be a good thing to be able to customize the default owners / users in a new project. This two migrations should be placed directly in Enso, not in the core package.

In next version (very soon) I will do this change.

**Comment by Aubrey-Robertson** [comment]
Thank you!
